services:
  mc-blueprint:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seanard-finance_tracker
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT:-3000}:3000"
